resolver: lts-5.12
packages:
- '.'
# TODO: have to drop this and depend on an officially released version of lcs
- location: https://github.com/juanpaucar/lcs/archive/40cc3bc32b5cd96d78f224850ec2d4428051b8b1.zip
  extra-dep: true
extra-deps:
  - katip-0.2.0.0
  - string-conv-0.1.1
# Override default flag values for local packages and extra-deps
flags:
  hadron:
    lib-Werror: True

# Extra package databases containing global packages
extra-package-dbs: []
